const ANGKOT_ROUTES = [
  { id:"R001", operator:"Angkot Umum", nomor:"01", warna:"Kuning", asal:"Simp. Permina", tujuan:"Lubuk Pakam", pp:false, waypoints:["Simp. Permina","Tanjung Morawa","Simp. Kayu Besar","Lubuk Pakam"] },
  { id:"R002", operator:"Angkot Umum", nomor:"02", warna:"Kuning", asal:"Jl. Karya", tujuan:"Perumnas Mandala", pp:false, waypoints:["Jl. Karya","Bundaran Sekip","Petisah","Plaza Medan Fair","Jl. Iskandar Muda","Simp. Brimob","Simp. Kampus","Padang Bulan","Simp. Pos","Titi Kuning","Simp. Limun","Jl. Sisingamangaraja","Jl. Halat","Jl. AR Hakim","Jl. Denai","Perumnas Mandala"] },
  { id:"R003", operator:"Angkot Umum", nomor:"03", warna:"Kuning", asal:"POLDASU", tujuan:"Sambu", pp:false, waypoints:["POLDASU","Amplas","Jl. Sisingamangaraja","Garuda Plaza Hotel","Sambu"] },
  { id:"R004", operator:"KPUM", nomor:"A03", warna:"Kuning", asal:"UNIMED", tujuan:"Pasar V Desa Martoba / Batas Kota", pp:false, waypoints:["UNIMED","Jl. Pancing","Aksara","Pasar V Desa Martoba / Batas Kota"] },
  { id:"R005", operator:"Angkot Umum", nomor:"N03", warna:"Kuning", asal:"Tuntungan", tujuan:"Lubuk Pakam", pp:false, waypoints:["Tuntungan","Lau Bakeri","Tanjung Anom","Pajak Melati","Simp. Pemda","Simp. Pos","Titi Kuning","Amplas","Tanjung Morawa","Lubuk Pakam"] },
  { id:"R006", operator:"POVRI", nomor:"04", warna:"-", asal:"Perum Indah / Eka Rasmi", tujuan:"Ikip Baru / Batas Kota", pp:true, waypoints:["Perum Indah / Eka Rasmi","Ikip Baru / Batas Kota"] },
  { id:"R007", operator:"KPUM", nomor:"05", warna:"Kuning", asal:"Jalan SM. Raja", tujuan:"Mariendal", pp:true, waypoints:["Jalan SM. Raja","Mariendal"] },
  { id:"R008", operator:"POVRI", nomor:"05", warna:"-", asal:"Deli Tua / Batas Kota", tujuan:"Veteran / Pajak Pasar", pp:true, waypoints:["Deli Tua / Batas Kota","Veteran / Pajak Pasar"] },
  { id:"R009", operator:"Angkot Umum", nomor:"06", warna:"Kuning", asal:"Pinang Baris", tujuan:"Amplas", pp:false, waypoints:["Pinang Baris","Pajak Melati","Simp. Pemda","Tanjung Sari","TASBI Pintu 1","Jl. Dr. Mansyur","USU","Simp. Kampus","Simp. Brimob","Jl. S. Parman","Jl. Monginsidi","Jl. Ir. H. Juanda","Jl. Sisingamangaraja","Amplas"] },
  { id:"R010", operator:"KPUM", nomor:"07", warna:"Kuning", asal:"T. Amplas", tujuan:"Tembung", pp:true, waypoints:["T. Amplas","Teladan","Letda Sujono / Batas Kota","Jl. Sisingamangaraja","Aksara","Jl. Pancing","Tembung"] },
  { id:"R011", operator:"CV Medan Kobun", nomor:"07", warna:"-", asal:"Tembung / Batas Kota", tujuan:"Veteran / Pajak Pasar", pp:true, waypoints:["Tembung / Batas Kota","Veteran / Pajak Pasar"] },
  { id:"R012", operator:"KPUM", nomor:"08", warna:"Kuning", asal:"Jl. Palang Merah", tujuan:"Deli Tua", pp:false, waypoints:["Jl. Palang Merah","B. Katamso","Istana Maimun","Pancing","Titi Kuning","Deli Tua"] },
  { id:"R013", operator:"KPUM", nomor:"10", warna:"Kuning", asal:"Perumnas Simalingkar", tujuan:"Aksara", pp:false, waypoints:["Perumnas Simalingkar","Simp. Pos","Padang Bulan","Simp. Kampus","Simp. Brimob","Pringgan","Jl. Hayam Wuruk","Jl. S. Parman","Jl. Jend. Sudirman","Taman Beringin","Kantor Gubernur","Sun Plaza","Simp. Selecta","Jl. Palang Merah","Jl. Sutomo","Sambu","Aksara"] },
  { id:"R014", operator:"KPUM", nomor:"11", warna:"Kuning", asal:"P. Simalingkar", tujuan:"Pancing / Batas Kota", pp:true, waypoints:["P. Simalingkar","Padang Bulan","Pringgan","Lapangan Merdeka","Pancing / Batas Kota"] },
  { id:"R015", operator:"KPUM", nomor:"13", warna:"Kuning", asal:"Tuntungan / Batas Kota", tujuan:"RS. Mina / UMA", pp:true, waypoints:["Tuntungan / Batas Kota","RS. Mina / UMA"] },
  { id:"R016", operator:"KPUM", nomor:"14", warna:"Kuning", asal:"Tembung", tujuan:"Tanjung Selamat / Batas Kota", pp:true, waypoints:["Tembung","Tanjung Selamat / Batas Kota"] },
  { id:"R017", operator:"KPUM", nomor:"17", warna:"Kuning", asal:"Karya Jasa / Batas Kota", tujuan:"Belawan", pp:true, waypoints:["Karya Jasa / Batas Kota","Belawan"] },
  { id:"R018", operator:"KPUM", nomor:"18", warna:"Kuning", asal:"Tanjung Selamat / Batas Kota", tujuan:"Perumnas Mandala", pp:true, waypoints:["Tanjung Selamat / Batas Kota","Perumnas Mandala"] },
  { id:"R019", operator:"KPUM", nomor:"23", warna:"Kuning", asal:"T. Pinang Baris", tujuan:"B. Katamso / Batas Kota", pp:true, waypoints:["T. Pinang Baris","B. Katamso / Batas Kota"] },
  { id:"R020", operator:"KPUM", nomor:"27", warna:"Kuning", asal:"Metrologi", tujuan:"Marendal / Batas Kota", pp:true, waypoints:["Metrologi","Marendal / Batas Kota"] },
  { id:"R021", operator:"KPUM", nomor:"28", warna:"Kuning", asal:"Letda Sujono / Batas Kota", tujuan:"Gabion", pp:true, waypoints:["Letda Sujono / Batas Kota","Gabion"] },
  { id:"R022", operator:"KPUM", nomor:"33", warna:"Kuning", asal:"Tuntungan / Batas Kota", tujuan:"Ringroad Potong", pp:true, waypoints:["Tuntungan / Batas Kota","Ringroad Potong"] },
  { id:"R023", operator:"KPUM", nomor:"35", warna:"Kuning", asal:"Tb. Sihombing / Batas Kota", tujuan:"T. Pinang Baris", pp:true, waypoints:["Tb. Sihombing / Batas Kota","T. Pinang Baris"] },
  { id:"R024", operator:"KPUM", nomor:"37", warna:"Kuning", asal:"Johor / Pasar V / Batas Kota", tujuan:"T. Belawan", pp:true, waypoints:["Johor / Pasar V / Batas Kota","T. Belawan"] },
  { id:"R025", operator:"KPUM", nomor:"38", warna:"Kuning", asal:"RS. Adam Malik", tujuan:"Desa Martoba / Batas Kota", pp:true, waypoints:["RS. Adam Malik","Desa Martoba / Batas Kota"] },
  { id:"R026", operator:"KPUM", nomor:"39", warna:"Kuning", asal:"T. Pinang Baris", tujuan:"Pertiwi / SMU XI / Batas Kota", pp:true, waypoints:["T. Pinang Baris","Pertiwi / SMU XI / Batas Kota"] },
  { id:"R027", operator:"KPUM", nomor:"40", warna:"Kuning", asal:"Kelambir Lima / Batas Kota", tujuan:"Perumnas Mandala", pp:true, waypoints:["Kelambir Lima / Batas Kota","Perumnas Mandala"] },
  { id:"R028", operator:"KPUM", nomor:"42", warna:"Kuning", asal:"Johor", tujuan:"Pasar VII", pp:false, waypoints:["Johor","STM","Simp. Limun","Pasar VII"] },
  { id:"R029", operator:"KPUM", nomor:"45", warna:"Kuning", asal:"Desa Simalingkar B", tujuan:"Letda Sujono / Batas Kota", pp:true, waypoints:["Desa Simalingkar B","Letda Sujono / Batas Kota"] },
  { id:"R030", operator:"KPUM", nomor:"46", warna:"Kuning", asal:"Tj. Selamat", tujuan:"Tembung", pp:true, waypoints:["Tj. Selamat","Sei Serayu","Jl. Darusalam","Gatot Subroto","Berastagi Swalayan","Letda Sujono","Tembung"] },
  { id:"R031", operator:"KPUM", nomor:"47", warna:"Kuning", asal:"T. Pinang Baris", tujuan:"Letda Sujono / Batas Kota", pp:true, waypoints:["T. Pinang Baris","Letda Sujono / Batas Kota"] },
  { id:"R032", operator:"KPUM", nomor:"50", warna:"Kuning", asal:"T. Pinang Baris", tujuan:"Jermal XI / Batas Kota", pp:true, waypoints:["T. Pinang Baris","Jermal XI / Batas Kota"] },
  { id:"R033", operator:"KPUM", nomor:"51", warna:"Kuning", asal:"T. Pinang Baris", tujuan:"Desa Jambu / Batas Kota", pp:true, waypoints:["T. Pinang Baris","Desa Jambu / Batas Kota"] },
  { id:"R034", operator:"KPUM", nomor:"52", warna:"Kuning", asal:"Padang Bulan", tujuan:"Pinang Baris", pp:false, waypoints:["Padang Bulan","Titi Kuning","Pringgan","Pinang Baris"] },
  { id:"R035", operator:"KPUM", nomor:"54", warna:"Kuning", asal:"Pasar VII Tj. M. Hilir", tujuan:"Tuntungan / Batas Kota", pp:true, waypoints:["Pasar VII Tj. M. Hilir","Tuntungan / Batas Kota"] },
  { id:"R036", operator:"KPUM", nomor:"55", warna:"Kuning", asal:"T. Amplas", tujuan:"Letda Sujono / Batas Kota", pp:true, waypoints:["T. Amplas","Letda Sujono / Batas Kota"] },
  { id:"R037", operator:"KPUM", nomor:"56", warna:"Kuning", asal:"Tj. Selamat", tujuan:"Lau Dendang / Batas Kota", pp:true, waypoints:["Tj. Selamat","Lau Dendang / Batas Kota"] },
  { id:"R038", operator:"KPUM", nomor:"57", warna:"Kuning", asal:"Tj. Selamat / Batas Kota", tujuan:"Perumnas Mandala", pp:true, waypoints:["Tj. Selamat / Batas Kota","Perumnas Mandala"] },
  { id:"R039", operator:"KPUM", nomor:"59", warna:"Kuning", asal:"Perumnas Mandala", tujuan:"B. Katamso / Batas Kota", pp:true, waypoints:["Perumnas Mandala","B. Katamso / Batas Kota"] },
  { id:"R040", operator:"KPUM", nomor:"60", warna:"Kuning", asal:"P. Simalingkar", tujuan:"Martoba / Batas Kota", pp:true, waypoints:["P. Simalingkar","Martoba / Batas Kota"] },
  { id:"R041", operator:"KPUM", nomor:"64", warna:"Kuning", asal:"Amplas", tujuan:"Pringgan", pp:false, waypoints:["Amplas","Simp. Limun","Sun Plaza","Pringgan"] },
  { id:"R042", operator:"KPUM", nomor:"65", warna:"Kuning", asal:"Kelambir V / Batas Kota", tujuan:"T. Pinang Baris", pp:true, waypoints:["Kelambir V / Batas Kota","T. Pinang Baris"] },
  { id:"R043", operator:"KPUM", nomor:"68", warna:"Kuning", asal:"Kelambir V / Batas Kota", tujuan:"Pertiwi / SMU XI", pp:true, waypoints:["Kelambir V / Batas Kota","Pertiwi / SMU XI"] },
  { id:"R044", operator:"KPUM", nomor:"72", warna:"Kuning", asal:"Simpang Bw / Batas Kota", tujuan:"T. Pinang Baris", pp:true, waypoints:["Simpang Bw / Batas Kota","T. Pinang Baris"] },
  { id:"R045", operator:"KPUM", nomor:"81", warna:"Kuning", asal:"P. Simalingkar", tujuan:"Tembung / Batas Kota", pp:true, waypoints:["P. Simalingkar","Tembung / Batas Kota"] },
  { id:"R046", operator:"KPUM", nomor:"84", warna:"Kuning", asal:"SMU XI Pertiwi", tujuan:"Tj. Selamat / Batas Kota", pp:true, waypoints:["SMU XI Pertiwi","Tj. Selamat / Batas Kota"] },
  { id:"R047", operator:"KPUM", nomor:"86", warna:"Kuning", asal:"T. Pinang Baris / Sentis / Batas Kota", tujuan:"T. Pinang Baris / Sentis / Batas Kota", pp:true, waypoints:["T. Pinang Baris / Sentis / Batas Kota"] },
  { id:"R048", operator:"KPUM", nomor:"87", warna:"Kuning", asal:"Denai Ujung Batas Kota", tujuan:"Belawan", pp:true, waypoints:["Denai Ujung Batas Kota","Belawan"] },
  { id:"R049", operator:"KPUM", nomor:"90", warna:"Kuning", asal:"Belawan", tujuan:"Deli Tua", pp:true, waypoints:["Belawan","Deli Tua"] },
  { id:"R050", operator:"KPUM", nomor:"91", warna:"Kuning", asal:"Sentis Bw / Batas Kota", tujuan:"T. Amplas", pp:true, waypoints:["Sentis Bw / Batas Kota","T. Amplas"] },
  { id:"R051", operator:"KPUM", nomor:"91B", warna:"Kuning", asal:"Pasar V Johor", tujuan:"Tb. Sihombing / Batas Kota", pp:true, waypoints:["Pasar V Johor","Tb. Sihombing / Batas Kota"] },
  { id:"R052", operator:"Medan Desa Maju", nomor:"45", warna:"-", asal:"Letda Sujono / Batas Kota", tujuan:"Jl. Gaperta", pp:true, waypoints:["Letda Sujono / Batas Kota","Jl. Gaperta"] },
  { id:"R053", operator:"Wampu Mini", nomor:"108", warna:"Kuning", asal:"Pasar II", tujuan:"Gatot Subroto", pp:true, waypoints:["Pasar II","Pajak Sore","Padang Bulan","Pringgan","Petisah","Plaza Medan Fair","Gaperta","Gatot Subroto"] },
  { id:"R054", operator:"Wampu Mini", nomor:"109", warna:"Kuning", asal:"T. Morawa / Batas Kota", tujuan:"Tj. Selamat / Batas Kota", pp:true, waypoints:["T. Morawa / Batas Kota","Tj. Selamat / Batas Kota"] },
  { id:"R055", operator:"Wampu Mini", nomor:"110", warna:"Kuning", asal:"Kolam Renang Morina", tujuan:"Klumpang / Batas Kota", pp:true, waypoints:["Kolam Renang Morina","Klumpang / Batas Kota"] },
  { id:"R056", operator:"Wampu Mini", nomor:"123", warna:"Kuning", asal:"Medan Permai / Batas Kota", tujuan:"Perum G. Martubung", pp:true, waypoints:["Medan Permai / Batas Kota","Perum G. Martubung"] },
  { id:"R057", operator:"Wampu Mini", nomor:"136", warna:"Kuning", asal:"T. Pinang Baris", tujuan:"Sei Rotan / Batas Kota", pp:true, waypoints:["T. Pinang Baris","Jl. Gatot Subroto","Sei Rotan / Batas Kota"] },
  { id:"R058", operator:"Wampu Mini", nomor:"137", warna:"Kuning", asal:"T. Morawa / Batas Kota", tujuan:"Tj. Anom / Batas Kota", pp:true, waypoints:["T. Morawa / Batas Kota","Tj. Anom / Batas Kota"] },
  { id:"R059", operator:"Wampu Mini", nomor:"168", warna:"Kuning", asal:"B. Katamso / Batas Kota", tujuan:"Belawan", pp:true, waypoints:["B. Katamso / Batas Kota","Belawan"] },
  { id:"R060", operator:"RMC (Rahayu Medan Ceria)", nomor:"41", warna:"Merah Hijau", asal:"Tembung / Batas Kota", tujuan:"RSU Adam Malik", pp:true, waypoints:["Tembung / Batas Kota","Jl. HM Yamin","Jl. Amaliun","Yuki Simpang Raya","Jl. Juanda","Jl. Monginsidi","USU","Padang Bulan","RSU Adam Malik"] },
  { id:"R061", operator:"RMC (Rahayu Medan Ceria)", nomor:"42", warna:"Merah Hijau", asal:"RSU Adam Malik", tujuan:"Komp. IKIP / Medan Estate / Batas Kota", pp:true, waypoints:["RSU Adam Malik","Pringgan","Komp. IKIP / Medan Estate / Batas Kota"] },
  { id:"R062", operator:"RMC (Rahayu Medan Ceria)", nomor:"43", warna:"Merah Hijau", asal:"P. Simalingkar / Batas Kota", tujuan:"Perumnas Mandala / Batas Kota", pp:true, waypoints:["P. Simalingkar / Batas Kota","Perumnas Mandala / Batas Kota"] },
  { id:"R063", operator:"RMC (Rahayu Medan Ceria)", nomor:"54", warna:"Merah Hijau", asal:"Desa Simalingkar", tujuan:"Komp. IKIP / Medan Estate", pp:true, waypoints:["Desa Simalingkar","Kebun Binatang Simalingkar","USU","Pringgan","Komp. IKIP / Medan Estate"] },
  { id:"R064", operator:"RMC (Rahayu Medan Ceria)", nomor:"58", warna:"Merah Hijau", asal:"Tj. Anom / Batas Kota", tujuan:"Tembung / Batas Kota", pp:true, waypoints:["Tj. Anom / Batas Kota","Tembung / Batas Kota"] },
  { id:"R065", operator:"RMC (Rahayu Medan Ceria)", nomor:"103", warna:"Merah Hijau", asal:"Ikip / Medan Estate", tujuan:"Pancur Batu", pp:true, waypoints:["Ikip / Medan Estate","Pancur Batu"] },
  { id:"R066", operator:"RMC (Rahayu Medan Ceria)", nomor:"104", warna:"Merah Hijau", asal:"Padang Bulan", tujuan:"UNIMED", pp:true, waypoints:["Padang Bulan","Pringgan","Aksara","UNIMED"] },
  { id:"R067", operator:"RMC (Rahayu Medan Ceria)", nomor:"105", warna:"Merah Hijau", asal:"Terminal Amplas", tujuan:"Komplek Uka Terjun", pp:true, waypoints:["Terminal Amplas","Marelan","Pancing","Aksara","Komplek Uka Terjun"] },
  { id:"R068", operator:"RMC (Rahayu Medan Ceria)", nomor:"106", warna:"Merah Hijau", asal:"Terminal Amplas", tujuan:"Perumnas Mandala", pp:true, waypoints:["Terminal Amplas","Perumnas Mandala"] },
  { id:"R069", operator:"RMC (Rahayu Medan Ceria)", nomor:"107", warna:"Merah Hijau", asal:"Pancur Batu", tujuan:"Perumnas Mandala", pp:true, waypoints:["Pancur Batu","Perumnas Mandala"] },
  { id:"R070", operator:"RMC (Rahayu Medan Ceria)", nomor:"120", warna:"Merah Hijau", asal:"T. Pinang Baris", tujuan:"Amplas", pp:true, waypoints:["T. Pinang Baris","Setia Budi","USU","Padang Bulan","Titi Kuning","Amplas"] },
  { id:"R071", operator:"RMC (Rahayu Medan Ceria)", nomor:"125", warna:"Merah Hijau", asal:"Medan Amplas", tujuan:"Medan Labuhan", pp:false, waypoints:["Medan Amplas","Martubung","Medan Labuhan"] },
  { id:"R072", operator:"Medan Bus", nomor:"11", warna:"Biru", asal:"T. Morawa / Batas Kota", tujuan:"Gabion", pp:true, waypoints:["T. Morawa / Batas Kota","Belawan","Gabion"] },
  { id:"R073", operator:"Medan Bus", nomor:"36", warna:"Biru", asal:"Karya Wisata", tujuan:"Tembung / Batas Kota", pp:true, waypoints:["Karya Wisata","Tembung / Batas Kota"] },
  { id:"R074", operator:"Medan Bus", nomor:"45", warna:"Biru", asal:"T. Pinang Baris", tujuan:"Tembung / Batas Kota", pp:true, waypoints:["T. Pinang Baris","Tembung / Batas Kota"] },
  { id:"R075", operator:"Medan Bus", nomor:"47", warna:"Biru", asal:"T. Pinang Baris", tujuan:"Perumnas Mandala / Batas Kota", pp:true, waypoints:["T. Pinang Baris","Perumnas Mandala / Batas Kota"] },
  { id:"R076", operator:"Medan Bus", nomor:"56", warna:"Biru", asal:"Tj. Morawa / Batas Kota", tujuan:"Gabion", pp:true, waypoints:["Tj. Morawa / Batas Kota","Belawan","Gabion"] },
  { id:"R077", operator:"Medan Bus", nomor:"135", warna:"Biru", asal:"Amplas", tujuan:"Helvetia", pp:true, waypoints:["Amplas","Padang Bulan","USU","Helvetia"] },
  { id:"R078", operator:"Medan Hikmah", nomor:"26", warna:"-", asal:"Desa Terjun / Batas Kota", tujuan:"T. Amplas", pp:true, waypoints:["Desa Terjun / Batas Kota","T. Amplas"] },
  { id:"R079", operator:"Medan Hikmah", nomor:"62", warna:"-", asal:"T. Amplas", tujuan:"Desa Terjun / Batas Kota", pp:true, waypoints:["T. Amplas","Desa Terjun / Batas Kota"] },
  { id:"R080", operator:"Medan Hikmah", nomor:"63", warna:"-", asal:"T. Belawan", tujuan:"Pancur Batu / Batas Kota", pp:true, waypoints:["T. Belawan","Pancur Batu / Batas Kota"] },
  { id:"R081", operator:"Medan Kobun", nomor:"62", warna:"-", asal:"Tuntungan / Batas Kota", tujuan:"T. Amplas", pp:true, waypoints:["Tuntungan / Batas Kota","T. Amplas"] },
  { id:"R082", operator:"Medan Kobun", nomor:"63", warna:"-", asal:"Kedai Durian / Batas Kota", tujuan:"T. Pinang Baris", pp:true, waypoints:["Kedai Durian / Batas Kota","T. Pinang Baris"] },
  { id:"R083", operator:"Nasional Medan Transport", nomor:"K04", warna:"Biru", asal:"P. Simalingkar", tujuan:"Simp. Bw / Batas Kota", pp:true, waypoints:["P. Simalingkar","Simp. Bw / Batas Kota"] },
  { id:"R084", operator:"Nasional Medan Transport", nomor:"25", warna:"Biru", asal:"Tj. Selamat / Batas Kota", tujuan:"Veteran / Pajak Pasar", pp:true, waypoints:["Tj. Selamat / Batas Kota","Veteran / Pajak Pasar"] },
  { id:"R085", operator:"Nasional Medan Transport", nomor:"M27/31", warna:"Biru", asal:"T. Morawa / Batas Kota", tujuan:"Tj. Selamat / Batas Kota", pp:true, waypoints:["T. Morawa / Batas Kota","Tj. Selamat / Batas Kota"] },
  { id:"R086", operator:"Nasional Medan Transport", nomor:"M28", warna:"Biru", asal:"P. III Simalingkar", tujuan:"Veteran / Pajak Pasar", pp:true, waypoints:["P. III Simalingkar","Jl. R. Saleh","Veteran / Pajak Pasar"] },
  { id:"R087", operator:"Nasional Medan Transport", nomor:"M29", warna:"Biru", asal:"Simp. Selayang", tujuan:"Letda Sujono / Batas Kota", pp:true, waypoints:["Simp. Selayang","Letda Sujono / Batas Kota"] },
  { id:"R088", operator:"Medan Morina", nomor:"75", warna:"Hijau", asal:"Batas Kota / Ikip Unimed", tujuan:"Bagan Deli", pp:true, waypoints:["Batas Kota / Ikip Unimed","Bagan Deli"] },
  { id:"R089", operator:"Medan Morina", nomor:"80", warna:"Hijau", asal:"Perumnas Martubung", tujuan:"Tj. Selamat / Batas Kota", pp:true, waypoints:["Perumnas Martubung","Jl. Sunggal","Tj. Selamat / Batas Kota"] },
  { id:"R090", operator:"Medan Morina", nomor:"81", warna:"Hijau", asal:"Amplas", tujuan:"Belawan", pp:false, waypoints:["Amplas","Belawan"] },
  { id:"R091", operator:"Medan Morina", nomor:"139", warna:"Hijau", asal:"Letda Sujono / Batas Kota", tujuan:"Terminal Belawan", pp:true, waypoints:["Letda Sujono / Batas Kota","Terminal Belawan"] },
  { id:"R092", operator:"Medan Morina", nomor:"140", warna:"Hijau", asal:"Terminal Pinang Baris", tujuan:"Letda Sujono / Batas Kota", pp:true, waypoints:["Terminal Pinang Baris","Letda Sujono / Batas Kota"] },
  { id:"R093", operator:"Medan Morina", nomor:"143", warna:"Hijau", asal:"Simalingkar B", tujuan:"Tembung / Batas Kota", pp:true, waypoints:["Simalingkar B","Tembung / Batas Kota"] },
  { id:"R094", operator:"Mitra Transport", nomor:"A97", warna:"Merah Kuning", asal:"Pancur Batu", tujuan:"Lubuk Pakam", pp:false, waypoints:["Pancur Batu","Amplas","Tanjung Morawa","Lubuk Pakam"] },
  { id:"R095", operator:"Mitra Transport", nomor:"141", warna:"Merah Kuning", asal:"Pancur Batu / Batas Kota", tujuan:"Perumnas Mandala / Batas Kota", pp:true, waypoints:["Pancur Batu / Batas Kota","Perumnas Mandala / Batas Kota"] },
  { id:"R096", operator:"Mitra Transport", nomor:"142", warna:"Merah Kuning", asal:"Pancur Batu / Batas Kota", tujuan:"Gabion Belawan", pp:true, waypoints:["Pancur Batu / Batas Kota","Gabion Belawan"] },
  { id:"R097", operator:"Mitra Transport", nomor:"143", warna:"Merah Kuning", asal:"Tembung Pasar X / Batas Kota", tujuan:"Tj. Anom / Batas Kota", pp:true, waypoints:["Tembung Pasar X / Batas Kota","Tj. Anom / Batas Kota"] },
  { id:"R098", operator:"Mitra Transport", nomor:"144", warna:"Merah Kuning", asal:"Desa Martoba", tujuan:"Desa Kelambir V / Batas Kota", pp:true, waypoints:["Desa Martoba","Desa Kelambir V / Batas Kota"] },
  { id:"R099", operator:"Mitra Transport", nomor:"145", warna:"Merah Kuning", asal:"Tj. Anom / Batas Kota", tujuan:"Tembung Pasar X / Batas Kota", pp:true, waypoints:["Tj. Anom / Batas Kota","Tembung Pasar X / Batas Kota"] },
  { id:"R100", operator:"Mitra Transport", nomor:"146", warna:"Merah Kuning", asal:"RSU Adam Malik", tujuan:"Hamparan Perak / Batas Kota", pp:true, waypoints:["RSU Adam Malik","Hamparan Perak / Batas Kota"] },
  { id:"R101", operator:"Mitra Transport", nomor:"63", warna:"Merah Kuning", asal:"Amplas", tujuan:"Pinang Baris", pp:false, waypoints:["Amplas","Padang Bulan","Pinang Baris"] },
  { id:"R102", operator:"Mitra Transport", nomor:"03", warna:"Merah Kuning", asal:"Simpang Pos", tujuan:"Simpang Melati", pp:false, waypoints:["Simpang Pos","Simpang Melati"] },
  { id:"R103", operator:"Mitra Transport", nomor:"30", warna:"Merah Kuning", asal:"Amplas", tujuan:"Belawan", pp:false, waypoints:["Amplas","Belawan"] },
  { id:"R104", operator:"Mekar Jaya", nomor:"116", warna:"Kuning", asal:"Pasar V / Batas Kota", tujuan:"Terjun / Batas Kota", pp:true, waypoints:["Pasar V / Batas Kota","Terjun / Batas Kota"] },
  { id:"R105", operator:"Medan Mars", nomor:"13", warna:"Hijau", asal:"Perumnas Mandala / Batas Kota", tujuan:"Tj. Gusta Sukadono", pp:true, waypoints:["Perumnas Mandala / Batas Kota","Tj. Gusta Sukadono"] },
  { id:"R106", operator:"Medan Mars", nomor:"60", warna:"Hijau", asal:"Aksara", tujuan:"Pasar I", pp:false, waypoints:["Aksara","Hayam Wuruk","Padang Bulan","Pasar I"] },
  { id:"R107", operator:"Medan Mars", nomor:"61", warna:"Hijau", asal:"Simalingkar", tujuan:"Belawan", pp:false, waypoints:["Simalingkar","Padang Bulan","Belawan"] },
  { id:"R108", operator:"Medan Mars", nomor:"65", warna:"Hijau", asal:"Tembung / Batas Kota", tujuan:"Bagan Deli / Belawan", pp:true, waypoints:["Tembung / Batas Kota","Bagan Deli / Belawan"] },
  { id:"R109", operator:"Medan Mars", nomor:"70", warna:"Hijau", asal:"Perumnas Mandala / Batas Kota", tujuan:"T. Pinang Baris", pp:true, waypoints:["Perumnas Mandala / Batas Kota","T. Pinang Baris"] },
  { id:"R110", operator:"Medan Mars", nomor:"71", warna:"Hijau", asal:"Tj. Gusta", tujuan:"Tembung / Batas Kota", pp:true, waypoints:["Tj. Gusta","Tembung / Batas Kota"] },
  { id:"R111", operator:"Medan Mars", nomor:"45", warna:"Hijau", asal:"B. Katamso / Batas Kota", tujuan:"Pasar V / Batas Kota", pp:true, waypoints:["B. Katamso / Batas Kota","Pasar V / Batas Kota"] },
  { id:"R112", operator:"Medan Mars", nomor:"128", warna:"Hijau", asal:"Letda Sujono / Batas Kota", tujuan:"Belawan / Gabion", pp:true, waypoints:["Letda Sujono / Batas Kota","Belawan / Gabion"] },
  { id:"R113", operator:"Medan Mars", nomor:"129", warna:"Hijau", asal:"B. Katamso / Batas Kota", tujuan:"Belawan / Gabion", pp:true, waypoints:["B. Katamso / Batas Kota","Belawan / Gabion"] },
  { id:"R114", operator:"Medan Mars", nomor:"130", warna:"Hijau", asal:"Tj. Selamat / Batas Kota", tujuan:"Belawan / Gabion", pp:true, waypoints:["Tj. Selamat / Batas Kota","Belawan / Gabion"] },
  { id:"R115", operator:"Medan Mars", nomor:"131", warna:"Hijau", asal:"Jamin Ginting / Batas Kota", tujuan:"Gabion", pp:true, waypoints:["Jamin Ginting / Batas Kota","Gabion"] },
  { id:"R116", operator:"Medan Mars", nomor:"133", warna:"Hijau", asal:"Tj. Selamat / Batas Kota", tujuan:"Pajak Pasar / Batas Kota", pp:true, waypoints:["Tj. Selamat / Batas Kota","Pajak Pasar / Batas Kota"] },
  { id:"R117", operator:"MRX", nomor:"-", warna:"Putih", asal:"Helvetia", tujuan:"Amplas", pp:false, waypoints:["Helvetia","Zipur","Jl. Kapt. Muslim","Jl. Gatot Subroto","Jl. Iskandar Muda","Jl. Gajah Mada","Jl. S. Parman","Palladium","Merdeka Walk","Stasiun Kereta Api","Pajak Ikan Lama","Cirebon","Garuda Plaza Hotel","Jl. Sisingamangaraja","Amplas"] },
  { id:"R118", operator:"Sandhra Frima", nomor:"-", warna:"Putih Hijau", asal:"Pancur Batu", tujuan:"Pagurawan", pp:false, waypoints:["Pancur Batu","Simp. RSUP Adam Malik","Simp. Selayang","Simp. Simalingkar","Simp. Pos","Titi Kuning","Amplas","Tanjung Morawa","Simp. Kayu Besar","Lubuk Pakam","Sei Rampah","Pagurawan"] }
];

const LIVERY_COLORS = {
  "Kuning":      { bg: "bg-[#ffd731]", text: "text-[#000000]", border: "border-[#ffd731]", hex: "#ffd731", label: "Kuning", lightBg: "bg-[#ffd731]/10" },
  "Biru":        { bg: "bg-[#4da2ff]", text: "text-white",     border: "border-[#4da2ff]", hex: "#4da2ff", label: "Biru",   lightBg: "bg-[#4da2ff]/10" },
  "Hijau":       { bg: "bg-[#55db9c]", text: "text-white",     border: "border-[#55db9c]", hex: "#55db9c", label: "Hijau",  lightBg: "bg-[#55db9c]/10" },
  "Merah Hijau": { bg: "bg-[#fb4903]", text: "text-white",     border: "border-[#fb4903]", hex: "#fb4903", label: "Merah Hijau", lightBg: "bg-[#fb4903]/10" },
  "Merah Kuning":{ bg: "bg-[#fb4903]", text: "text-[#ffd731]", border: "border-[#fb4903]", hex: "#fb4903", label: "Merah Kuning", lightBg: "bg-[#fb4903]/10" },
  "Putih":       { bg: "bg-white",     text: "text-[#000000]", border: "border-[#cccccc]",  hex: "#FFFFFF", label: "Putih",  lightBg: "bg-[#dceeff]" },
  "Putih Hijau": { bg: "bg-white",     text: "text-[#55db9c]", border: "border-[#55db9c]", hex: "#FFFFFF", label: "Putih Hijau", lightBg: "bg-[#55db9c]/5" },
  "-":           { bg: "bg-[#cccccc]",  text: "text-[#000000]", border: "border-[#cccccc]",  hex: "#D1D5DB", label: "-",     lightBg: "bg-[#dceeff]" }
};

const POPULAR_ROUTES = [
  { from: "USU", to: "Amplas" },
  { from: "Pinang Baris", to: "Amplas" },
  { from: "Simp. Pos", to: "Perumnas Mandala" },
  { from: "Padang Bulan", to: "Tembung" },
  { from: "Helvetia", to: "Amplas" },
  { from: "Terminal Amplas", to: "Belawan" },
  { from: "RS. Adam Malik", to: "Tembung" },
  { from: "Simp. Pos", to: "Belawan" },
  { from: "T. Pinang Baris", to: "Letda Sujono" }
];

const ALL_STOPS = (() => {
  const s = new Set();
  ANGKOT_ROUTES.forEach(r => r.waypoints.forEach(w => s.add(w)));
  return [...s].sort();
})();

const STOP_COORDS = {
  "Aksara": [3.5989, 98.7091],
  "Amplas": [3.5493, 98.7167],
  "B. Katamso": [3.5884, 98.6921],
  "B. Katamso / Batas Kota": [3.5884, 98.6921],
  "Bagan Deli": [3.774, 98.7042],
  "Bagan Deli / Belawan": [3.774, 98.7042],
  "Batas Kota / Ikip Unimed": [3.57, 98.67],
  "Belawan": [3.7867, 98.6957],
  "Belawan / Gabion": [3.71, 98.69],
  "Berastagi Swalayan": [3.598, 98.71],
  "Bundaran Sekip": [3.5920, 98.6580],
  "Cirebon": [3.5836, 98.684],
  "Deli Tua": [3.4976, 98.6819],
  "Deli Tua / Batas Kota": [3.4976, 98.6819],
  "Denai Ujung Batas Kota": [3.5592, 98.7042],
  "Desa Jambu": [3.53, 98.78],
  "Desa Jambu / Batas Kota": [3.53, 98.78],
  "Desa Kelambir V": [3.592, 98.708],
  "Desa Kelambir V / Batas Kota": [3.592, 98.708],
  "Desa Martoba": [3.53, 98.78],
  "Desa Martoba / Batas Kota": [3.53, 98.78],
  "Desa Simalingkar": [3.612, 98.638],
  "Desa Simalingkar B": [3.615, 98.635],
  "Desa Terjun": [3.535, 98.765],
  "Desa Terjun / Batas Kota": [3.535, 98.765],
  "Gabion": [3.71, 98.69],
  "Gabion Belawan": [3.71, 98.69],
  "Gaperta": [3.6048, 98.6456],
  "Garuda Plaza Hotel": [3.5785, 98.6861],
  "Gatot Subroto": [3.5945, 98.6174],
  "Hamparan Perak / Batas Kota": [3.7441, 98.5701],
  "Hayam Wuruk": [3.5816, 98.6679],
  "Helvetia": [3.607, 98.6305],
  "Ikip / Medan Estate": [3.57, 98.67],
  "Ikip Baru": [3.565, 98.66],
  "Ikip Baru / Batas Kota": [3.565, 98.66],
  "Istana Maimun": [3.5752, 98.6838],
  "Jalan SM. Raja": [3.58, 98.685],
  "Jamin Ginting / Batas Kota": [3.62, 98.62],
  "Jermal XI / Batas Kota": [3.5733, 98.745],
  "Jl. Amaliun": [3.5761, 98.6955],
  "Jl. AR Hakim": [3.575, 98.705],
  "Jl. Darusalam": [3.555, 98.718],
  "Jl. Denai": [3.5819, 98.7094],
  "Jl. Dr. Mansyur": [3.57, 98.665],
  "Jl. Gajah Mada": [3.5849, 98.6544],
  "Jl. Gaperta": [3.6048, 98.6456],
  "Jl. Gatot Subroto": [3.5911, 98.6355],
  "Jl. Halat": [3.5723, 98.7015],
  "Jl. Hayam Wuruk": [3.5816, 98.6654],
  "Jl. HM Yamin": [3.578, 98.695],
  "Jl. Ir. H. Juanda": [3.57, 98.675],
  "Jl. Iskandar Muda": [3.5896, 98.6615],
  "Jl. Jend. Sudirman": [3.5769, 98.6678],
  "Jl. Juanda": [3.573, 98.6717],
  "Jl. Kapt. Muslim": [3.6028, 98.6454],
  "Jl. Karya": [3.6009, 98.6139],
  "Jl. Monginsidi": [3.5712, 98.6718],
  "Jl. Palang Merah": [3.5842, 98.678],
  "Jl. Pancing": [3.6001, 98.7204],
  "Jl. R. Saleh": [3.62, 98.61],
  "Jl. S. Parman": [3.5803, 98.6674],
  "Jl. Sisingamangaraja": [3.5377, 98.7092],
  "Jl. Sunggal": [3.5874, 98.6423],
  "Jl. Sutomo": [3.5847, 98.6868],
  "Johor": [3.5285, 98.6715],
  "Johor / Pasar V / Batas Kota": [3.5285, 98.6715],
  "Kantor Gubernur": [3.5808, 98.6717],
  "Karya Jasa": [3.544, 98.869],
  "Karya Jasa / Batas Kota": [3.5440, 98.8690],
  "Karya Wisata": [3.5385, 98.663],
  "Kebun Binatang Simalingkar": [3.608, 98.642],
  "Kedai Durian": [3.52, 98.625],
  "Kedai Durian / Batas Kota": [3.52, 98.625],
  "Kelambir Lima / Batas Kota": [3.6128, 98.6056],
  "Kelambir V / Batas Kota": [3.5924, 98.7083],
  "Klumpang / Batas Kota": [3.53, 98.75],
  "Kolam Renang Morina": [3.56, 98.7],
  "Komp. IKIP / Medan Estate": [3.57, 98.67],
  "Komp. IKIP / Medan Estate / Batas Kota": [3.57, 98.67],
  "Komplek Uka Terjun": [3.535, 98.765],
  "Lapangan Merdeka": [3.5903, 98.6787],
  "Lau Bakeri": [3.52, 98.62],
  "Lau Dendang / Batas Kota": [3.54, 98.74],
  "Letda Sujono": [3.5978, 98.7091],
  "Letda Sujono / Batas Kota": [3.5978, 98.7091],
  "Lubuk Pakam": [3.5645, 98.8784],
  "Marelan": [3.7156, 98.656],
  "Marendal / Batas Kota": [3.648, 98.653],
  "Mariendal": [3.57, 98.68],
  "Martoba / Batas Kota": [3.53, 98.78],
  "Martubung": [3.64, 98.635],
  "Medan Amplas": [3.5493, 98.7167],
  "Medan Labuhan": [3.7199, 98.6936],
  "Medan Permai / Batas Kota": [3.58, 98.64],
  "Merdeka Walk": [3.5914, 98.6791],
  "Metrologi": [3.575, 98.67],
  "P. III Simalingkar": [3.618, 98.633],
  "P. Simalingkar": [3.61, 98.64],
  "P. Simalingkar / Batas Kota": [3.61, 98.64],
  "Padang Bulan": [3.5554, 98.6613],
  "Pagurawan": [3.5, 98.83],
  "Pajak Ikan Lama": [3.59, 98.68],
  "Pajak Melati": [3.555, 98.655],
  "Pajak Pasar": [3.573, 98.704],
  "Pajak Pasar / Batas Kota": [3.5728, 98.7041],
  "Pajak Sore": [3.6154, 98.7071],
  "Palladium": [3.5902, 98.6739],
  "Pancing": [3.6001, 98.7204],
  "Pancing / Batas Kota": [3.6, 98.72],
  "Pancur Batu": [3.565, 98.62],
  "Pancur Batu / Batas Kota": [3.565, 98.62],
  "Pasar I": [3.5919, 98.6943],
  "Pasar II": [3.5728, 98.7041],
  "Pasar V / Batas Kota": [3.7108, 98.6596],
  "Pasar V Desa Martoba / Batas Kota": [3.5300, 98.7800],
  "Pasar V Johor": [3.5142, 98.6511],
  "Pasar VII": [3.5427, 98.6526],
  "Pasar VII Tj. M. Hilir": [3.543, 98.653],
  "Pertiwi / SMU XI": [3.535, 98.77],
  "Pertiwi / SMU XI / Batas Kota": [3.535, 98.77],
  "Perum G. Martubung": [3.64, 98.632],
  "Perum Indah": [3.711, 98.675],
  "Perum Indah / Eka Rasmi": [3.711, 98.675],
  "Perumnas Mandala": [3.56, 98.72],
  "Perumnas Mandala / Batas Kota": [3.56, 98.72],
  "Perumnas Martubung": [3.6400, 98.6320],
  "Perumnas Simalingkar": [3.61, 98.64],
  "Petisah": [3.5927, 98.658],
  "Pinang Baris": [3.59, 98.6103],
  "Plaza Medan Fair": [3.5929, 98.6637],
  "POLDASU": [3.5362, 98.7747],
  "Pringgan": [3.575, 98.668],
  "Ringroad Potong": [3.58, 98.61],
  "RS. Adam Malik": [3.5492, 98.6618],
  "RS. Mina / UMA": [3.52, 98.615],
  "RSU Adam Malik": [3.5492, 98.6618],
  "Sambu": [3.588, 98.6825],
  "Sei Rampah": [3.51, 98.81],
  "Sei Rotan / Batas Kota": [3.607, 98.7866],
  "Sei Serayu": [3.5768, 98.6437],
  "Sentis Bw / Batas Kota": [3.59, 98.61],
  "Setia Budi": [3.575, 98.665],
  "Simalingkar": [3.612, 98.638],
  "Simalingkar B": [3.615, 98.635],
  "Simp. Brimob": [3.575, 98.67],
  "Simp. Bw / Batas Kota": [3.59, 98.71],
  "Simp. Kampus": [3.565, 98.66],
  "Simp. Kayu Besar": [3.5300, 98.7700],
  "Simp. Limun": [3.557, 98.6973],
  "Simp. Pemda": [3.55, 98.73],
  "Simp. Permina": [3.6200, 98.6300],
  "Simp. Pos": [3.5403, 98.6544],
  "Simp. RSUP Adam Malik": [3.553, 98.66],
  "Simp. Selayang": [3.5227, 98.6198],
  "Simp. Selecta": [3.578, 98.675],
  "Simp. Simalingkar": [3.61, 98.64],
  "Simpang Bw": [3.59, 98.71],
  "Simpang Bw / Batas Kota": [3.59, 98.71],
  "Simpang Melati": [3.58, 98.67],
  "Simpang Pos": [3.5403, 98.6544],
  "SMU XI Pertiwi": [3.535, 98.77],
  "Stasiun Kereta Api": [3.5898, 98.68],
  "STM": [3.5458, 98.6918],
  "Sun Plaza": [3.5823, 98.6719],
  "T. Amplas": [3.5391, 98.7182],
  "T. Belawan": [3.7867, 98.6957],
  "T. Morawa / Batas Kota": [3.526, 98.746],
  "T. Pinang Baris": [3.59, 98.6103],
  "T. Pinang Baris / Sentis / Batas Kota": [3.59, 98.6103],
  "Taman Beringin": [3.5763, 98.6693],
  "Tanjung Anom": [3.5213, 98.5874],
  "Tanjung Morawa": [3.5259, 98.7464],
  "Tanjung Sari": [3.5589, 98.6353],
  "Tanjung Selamat / Batas Kota": [3.543, 98.604],
  "TASBI Pintu 1": [3.565, 98.665],
  "Tb. Sihombing": [3.54, 98.76],
  "Tb. Sihombing / Batas Kota": [3.54, 98.76],
  "Teladan": [3.5649, 98.6955],
  "Tembung": [3.5948, 98.7348],
  "Tembung / Batas Kota": [3.595, 98.735],
  "Tembung Pasar X / Batas Kota": [3.595, 98.735],
  "Terjun / Batas Kota": [3.535, 98.765],
  "Terminal Amplas": [3.5391, 98.7182],
  "Terminal Belawan": [3.7867, 98.6957],
  "Terminal Pinang Baris": [3.59, 98.6103],
  "Titi Kuning": [3.534, 98.6842],
  "Tj. Anom / Batas Kota": [3.6005, 98.6905],
  "Tj. Gusta": [3.6092, 98.6093],
  "Tj. Gusta Sukadono": [3.609, 98.609],
  "Tj. Morawa / Batas Kota": [3.526, 98.746],
  "Tj. Selamat": [3.543, 98.6044],
  "Tj. Selamat / Batas Kota": [3.543, 98.6044],
  "Tuntungan": [3.5152, 98.6127],
  "Tuntungan / Batas Kota": [3.5152, 98.6127],
  "UNIMED": [3.609, 98.7171],
  "USU": [3.5613, 98.6568],
  "Veteran / Pajak Pasar": [3.58, 98.68],
  "Yuki Simpang Raya": [3.5758, 98.6884],
  "Zipur": [3.6111, 98.6451]
};

const PUBLIC_TRANSPORT = [
  { id:"TMD1", name:"Trans Metro Deli 1", type:"BRT", color:"#0066cc", icon:"bus", waypoints:["T. Pinang Baris","Jl. Gatot Subroto","Lap. Merdeka","Sun Plaza","Stasiun KA","Pajak Ikan Lama","Plaza Medan Fair","T. Amplas"] },
  { id:"TMD2", name:"Trans Metro Deli 2", type:"BRT", color:"#0066cc", icon:"bus", waypoints:["T. Pinang Baris","Jl. Gatot Subroto","Lap. Merdeka","Sun Plaza","Padang Bulan","Tj. Selamat"] },
  { id:"TMD3", name:"Trans Metro Deli 3", type:"BRT", color:"#0066cc", icon:"bus", waypoints:["T. Pinang Baris","Jl. Gatot Subroto","Lap. Merdeka","Sun Plaza","Padang Bulan","Simp. Pos","Tembung"] },
  { id:"TMD4", name:"Trans Metro Deli 4", type:"BRT", color:"#0066cc", icon:"bus", waypoints:["T. Belawan","Belawan","Gabion","Pancur Batu","Simp. Selayang","Simp. Pos","Padang Bulan"] },
  { id:"TMD5", name:"Trans Metro Deli 5", type:"BRT", color:"#0066cc", icon:"bus", waypoints:["T. Amplas","Jl. Sisingamangaraja","Merdeka Walk","Lap. Merdeka","Padang Bulan","Helvetia","T. Pinang Baris"] },
  { id:"TMD6", name:"Trans Metro Deli 6", type:"BRT", color:"#0066cc", icon:"bus", waypoints:["T. Pinang Baris","Jl. Gatot Subroto","Lap. Merdeka","Sun Plaza","RSU Adam Malik","Pringgan","Pancur Batu"] },
  { id:"TMD7", name:"Trans Metro Deli 7", type:"BRT", color:"#0066cc", icon:"bus", waypoints:["T. Pinang Baris","Jl. Gatot Subroto","Lap. Merdeka","Sun Plaza","Padang Bulan","Pancur Batu"] },
  { id:"BL1", name:"Bus Listrik Medan 1", type:"Listrik", color:"#00cc66", icon:"zap", waypoints:["T. Pinang Baris","Jl. Gatot Subroto","Lap. Merdeka","Stasiun KA","Merdeka Walk","Sun Plaza","Padang Bulan","USU"] },
  { id:"BL2", name:"Bus Listrik Medan 2", type:"Listrik", color:"#00cc66", icon:"zap", waypoints:["T. Amplas","Jl. Sisingamangaraja","Merdeka Walk","Lap. Merdeka","Sun Plaza","Padang Bulan","Tj. Selamat"] },
  { id:"BL3", name:"Bus Listrik Medan 3", type:"Listrik", color:"#00cc66", icon:"zap", waypoints:["T. Belawan","Belawan","Gabion","Pancur Batu","Simp. Selayang","Padang Bulan","Sun Plaza","Lap. Merdeka","T. Pinang Baris"] },
];

const TRANSPORT_COLORS = {
  angkot: { border: "#000000", label: "Angkot", icon: "bus" },
  brt: { border: "#0066cc", label: "BRT", icon: "bus" },
  listrik: { border: "#00cc66", label: "Bus Listrik", icon: "zap" },
};
